version: '3.8'

services:
  app:
    build: .
    container_name: sms-man-clone-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - sms-man-network

  db:
    image: postgres:15-alpine
    container_name: sms-man-clone-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-smsmanclone}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - sms-man-network

  nginx:
    image: nginx:alpine
    container_name: sms-man-clone-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - sms-man-network

volumes:
  postgres_data:

networks:
  sms-man-network:
    driver: bridge
